name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          BASE_URL: '/${{ github.event.repository.name }}/preview/${{ github.head_ref }}'

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: website
          path: dist
          if-no-files-found: error

  preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: Preview
      url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/${{ github.head_ref }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Download Website Artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: dist

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -a -e preview/$GITHUB_HEAD_REF -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: [build, preview]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format:ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build, preview]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build, preview]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run test:ci
